In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler , LabelEncoder
import pickle

In [2]:
data = pd.read_csv("Churn_Modelling.csv")
data.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [3]:
## preprocess the data
## Drop  irrelevant Columns
data = data.drop(['RowNumber','CustomerId','Surname'] ,axis=1 )
data

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...
235,771,France,Male,39,5,0.00,2,1,0,96270.64,0
236,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
237,709,France,Female,36,7,0.00,1,0,1,42085.58,1
238,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
239,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [4]:
## Encoding categorical variables
label_encoder_gender = LabelEncoder()
data['Gender'] = label_encoder_gender.fit_transform(data['Gender'])
data

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,0,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,0,41,1,83807.86,1,0,1,112542.58,0
2,502,France,0,42,8,159660.80,3,1,0,113931.57,1
3,699,France,0,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,0,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...
235,771,France,1,39,5,0.00,2,1,0,96270.64,0
236,516,France,1,35,10,57369.61,1,1,1,101699.77,0
237,709,France,0,36,7,0.00,1,0,1,42085.58,1
238,772,Germany,1,42,3,75075.31,2,1,0,92888.52,1
239,792,France,0,28,4,130142.79,1,1,0,38190.78,0

In [5]:
## One hot encoding 
from sklearn.preprocessing import OneHotEncoder
onehot_encoding_geo = OneHotEncoder()
geo_encoder = onehot_encoding_geo.fit_transform(data[['Geography']])
geo_encoder

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 240 stored elements and shape (240, 3)>

In [6]:
geo_encoder.toarray()

array([[1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.]])

In [7]:
onehot_encoding_geo.get_feature_names_out(['Geography'])

array(['Geography_France', 'Geography_Germany', 'Geography_Spain'],
      dtype=object)

In [8]:
geo_encoder_df = pd.DataFrame(geo_encoder.toarray(),columns=onehot_encoding_geo.get_feature_names_out(['Geography']))

In [9]:
geo_encoder_df

     Geography_France  Geography_Germany  Geography_Spain
0                 1.0                0.0              0.0
1                 0.0                0.0              1.0
2                 1.0                0.0              0.0
3                 1.0                0.0              0.0
4                 0.0                0.0              1.0
..                ...                ...              ...
235               1.0                0.0              0.0
236               1.0                0.0              0.0
237               1.0                0.0              0.0
238               0.0                1.0              0.0
239               1.0                0.0              0.0

[240 rows x 3 columns]

In [10]:
data = pd.concat([data.drop('Geography' ,axis=1), geo_encoder_df ] , axis=1)
data.head()

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,101348.88,1,1.0,0.0,0.0
1,608,0,41,1,83807.86,1,0,1,112542.58,0,0.0,0.0,1.0
2,502,0,42,8,159660.80,3,1,0,113931.57,1,1.0,0.0,0.0
3,699,0,39,1,0.00,2,0,0,93826.63,0,1.0,0.0,0.0
4,850,0,43,2,125510.82,1,1,1,79084.10,0,0.0,0.0,1.0

In [11]:
## Save the encoders abd scaler 
with open('label_encoder_gender.pkl','wb') as file:
    pickle.dump(label_encoder_gender,file)


with open('onehot_encoding_geo.pkl','wb') as file:
    pickle.dump(onehot_encoding_geo , file)

In [12]:
## Divide the dataset into indepdent and dependent features 
X = data.drop('Exited',axis=1)
Y = data['Exited']

## Split the data in training and testing sets 
X_train , X_test , Y_train , Y_test = train_test_split(X,Y,test_size=0.2,random_state=42)

scaler = StandardScaler(copy=True, with_mean=True, with_std=True)
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [13]:
print(X_train)
print(X_test)

[[-0.63049937 -0.98963703 -0.3176202  ... -0.91986621 -0.6336086
   1.70832296]
 [ 0.93778138  1.01047149 -0.3176202  ... -0.91986621  1.57826141
  -0.58536941]
 [-1.5926348   1.01047149 -0.42312726 ...  1.08711461 -0.6336086
  -0.58536941]
 ...
 [-1.15967386 -0.98963703 -0.21211314 ...  1.08711461 -0.6336086
  -0.58536941]
 [ 1.05323763 -0.98963703  1.79252092 ... -0.91986621  1.57826141
  -0.58536941]
 [ 0.89929596  1.01047149 -0.73964842 ...  1.08711461 -0.6336086
  -0.58536941]]
[[ 1.93840222e+00 -9.89637026e-01 -1.09903183e-03 -7.82352433e-02
  -1.24829028e+00 -9.07392872e-01  7.23746864e-01  1.07578035e+00
   1.46858010e+00  1.08711461e+00 -6.33608597e-01 -5.85369407e-01]
 [ 1.70748972e+00  1.01047149e+00  1.26498564e+00  6.20423674e-01
  -1.24829028e+00  8.00640769e-01  7.23746864e-01  1.07578035e+00
  -1.59144206e+00  1.08711461e+00 -6.33608597e-01 -5.85369407e-01]
 [ 1.19755794e+00  1.01047149e+00 -9.50662536e-01  9.69753132e-01
  -1.24829028e+00  8.00640769e-01  7.23746864e-01  1.07578035e+00
   1.20445374e+00  1.08711461e+00 -6.33608597e-01 -5.85369407e-01]
 [-1.59263480e+00  1.01047149e+00 -3.17620200e-01  1.31908259e+00
   2.58789019e-01 -9.07392872e-01  7.23746864e-01 -9.29557782e-01
  -5.09114559e-02 -9.19866211e-01  1.57826141e+00 -5.85369407e-01]
 [ 2.45043867e-01 -9.89637026e-01  2.84759148e+00 -1.47555308e+00
  -1.24829028e+00 -9.07392872e-01  7.23746864e-01  1.07578035e+00
   1.29691740e+00 -9.19866211e-01 -6.33608597e-01  1.70832296e+00]
 [-1.58301345e+00  1.01047149e+00  6.31943304e-01  1.66841205e+00
   8.55794691e-01 -9.07392872e-01  7.23746864e-01 -9.29557782e-01
  -1.67054959e+00 -9.19866211e-01  1.57826141e+00 -5.85369407e-01]
 [-5.11134447e-03  1.01047149e+00 -1.05616959e+00  6.20423674e-01
   1.26898368e+00 -9.07392872e-01  7.23746864e-01 -9.29557782e-01
  -1.26197723e+00  1.08711461e+00 -6.33608597e-01 -5.85369407e-01]
 [ 1.01475221e+00  1.01047149e+00 -1.68921193e+00 -7.76894160e-01
   7.27110642e-01 -9.07392872e-01  7.23746864e-01 -9.29557782e-01
   4.52220258e-01 -9.19866211e-01 -6.33608597e-01  1.70832296e+00]
 [ 3.79742827e-01  1.01047149e+00 -1.16167665e+00 -1.12622362e+00
   9.36889303e-01 -9.07392872e-01  7.23746864e-01  1.07578035e+00
  -5.28719660e-01  1.08711461e+00 -6.33608597e-01 -5.85369407e-01]
 [ 1.42847044e+00  1.01047149e+00  1.47599975e+00 -1.12622362e+00
  -1.24829028e+00 -9.07392872e-01  7.23746864e-01 -9.29557782e-01
   9.77532274e-01 -9.19866211e-01 -6.33608597e-01  1.70832296e+00]
 [ 1.26490742e+00 -9.89637026e-01 -6.34141368e-01 -4.27564702e-01
   5.28068762e-01  8.00640769e-01  7.23746864e-01  1.07578035e+00
   4.15581861e-01 -9.19866211e-01  1.57826141e+00 -5.85369407e-01]
 [-1.59263480e+00  1.01047149e+00 -3.17620200e-01 -4.27564702e-01
   7.95929802e-01 -9.07392872e-01  7.23746864e-01  1.07578035e+00
  -1.41339988e+00 -9.19866211e-01 -6.33608597e-01  1.70832296e+00]
 [ 7.35732936e-01  1.01047149e+00 -1.05616959e+00  1.31908259e+00
   1.25948881e+00  8.00640769e-01 -1.38169856e+00  1.07578035e+00
  -1.90092389e-02 -9.19866211e-01  1.57826141e+00 -5.85369407e-01]
 [ 2.16179804e-01 -9.89637026e-01  1.04408024e-01 -1.12622362e+00
  -1.24829028e+00  8.00640769e-01  7.23746864e-01 -9.29557782e-01
  -1.06306284e+00 -9.19866211e-01 -6.33608597e-01  1.70832296e+00]
 [ 2.93150638e-01  1.01047149e+00 -2.12113144e-01  1.31908259e+00
   4.75623041e-01 -9.07392872e-01 -1.38169856e+00  1.07578035e+00
  -1.36857532e+00 -9.19866211e-01 -6.33608597e-01  1.70832296e+00]
 [ 6.68383456e-01  1.01047149e+00 -5.28634312e-01 -7.76894160e-01
  -6.79825540e-01 -9.07392872e-01  7.23746864e-01 -9.29557782e-01
  -8.39949305e-01 -9.19866211e-01  1.57826141e+00 -5.85369407e-01]
 [-1.25588740e+00  1.01047149e+00 -6.34141368e-01  9.69753132e-01
  -1.24829028e+00  8.00640769e-01  7.23746864e-01 -9.29557782e-01
  -1.12829070e-01  1.08711461e+00 -6.33608597e-01 -5.85369407e-01]
 [-2.74509265e-01  1.01047149e+00  7.37450360e-01 -7.76894160e-01
   1.07529404e+00  8.00640769e-01 -1.38169856e+00  1.07578035e+00
  -6.56227707e-01 -9.19866211e-01  1.57826141e+00 -5.85369407e-01]
 [ 6.87626164e-01  1.01047149e+00  4.20929192e-01  9.69753132e-01
  -1.24829028e+00  8.00640769e-01  7.23746864e-01 -9.29557782e-01
   1.35111505e+00 -9.19866211e-01 -6.33608597e-01  1.70832296e+00]
 [-2.04483845e+00  1.01047149e+00  4.20929192e-01  1.31908259e+00
   1.22909702e+00 -9.07392872e-01  7.23746864e-01 -9.29557782e-01
   1.35484918e-01  1.08711461e+00 -6.33608597e-01 -5.85369407e-01]
 [-1.87917076e-01  1.01047149e+00  1.89802798e+00 -1.82488254e+00
   1.16259853e+00 -9.07392872e-01  7.23746864e-01 -9.29557782e-01
  -9.57884171e-01 -9.19866211e-01  1.57826141e+00 -5.85369407e-01]
 [ 7.83839707e-01 -9.89637026e-01 -1.47819782e+00  2.71094215e-01
  -1.24829028e+00  8.00640769e-01  7.23746864e-01  1.07578035e+00
  -8.21733427e-01  1.08711461e+00 -6.33608597e-01 -5.85369407e-01]
 [ 1.21680065e+00  1.01047149e+00  1.04408024e-01 -7.82352433e-02
  -1.24829028e+00  8.00640769e-01  7.23746864e-01 -9.29557782e-01
  -1.05703343e-01  1.08711461e+00 -6.33608597e-01 -5.85369407e-01]
 [-5.15043122e-01 -9.89637026e-01  1.04408024e-01 -7.76894160e-01
  -1.24829028e+00  2.50867441e+00  7.23746864e-01 -9.29557782e-01
   6.56034558e-01 -9.19866211e-01 -6.33608597e-01  1.70832296e+00]
 [-1.29437282e+00 -9.89637026e-01 -8.45155480e-01 -1.82488254e+00
  -1.24829028e+00  8.00640769e-01  7.23746864e-01  1.07578035e+00
   4.85139993e-01  1.08711461e+00 -6.33608597e-01 -5.85369407e-01]
 [ 1.05323763e+00 -9.89637026e-01 -6.34141368e-01  6.20423674e-01
  -1.24829028e+00  8.00640769e-01  7.23746864e-01 -9.29557782e-01
  -2.22033515e-01 -9.19866211e-01 -6.33608597e-01  1.70832296e+00]
 [-1.12118844e+00  1.01047149e+00 -7.39648424e-01  2.71094215e-01
   4.07864459e-01  8.00640769e-01 -1.38169856e+00 -9.29557782e-01
  -3.82996252e-01  1.08711461e+00 -6.33608597e-01 -5.85369407e-01]
 [-6.88227499e-01  1.01047149e+00  6.31943304e-01  1.31908259e+00
  -1.24829028e+00  8.00640769e-01  7.23746864e-01 -9.29557782e-01
   8.13505224e-02 -9.19866211e-01 -6.33608597e-01  1.70832296e+00]
 [ 6.20276684e-01 -9.89637026e-01 -2.12113144e-01  6.20423674e-01
  -1.24829028e+00 -9.07392872e-01 -1.38169856e+00  1.07578035e+00
  -1.03954928e+00  1.08711461e+00 -6.33608597e-01 -5.85369407e-01]
 [-1.01535354e+00  1.01047149e+00 -1.06606088e-01 -1.12622362e+00
   8.23342950e-01 -9.07392872e-01  7.23746864e-01 -9.29557782e-01
  -6.47616934e-02  1.08711461e+00 -6.33608597e-01 -5.85369407e-01]
 [ 1.23604336e+00  1.01047149e+00  3.15422136e-01  1.31908259e+00
   4.21025809e-01 -9.07392872e-01 -1.38169856e+00  1.07578035e+00
  -6.51609066e-01 -9.19866211e-01 -6.33608597e-01  1.70832296e+00]
 [ 1.25528607e+00  1.01047149e+00 -8.45155480e-01 -4.27564702e-01
  -1.24829028e+00  8.00640769e-01  7.23746864e-01 -9.29557782e-01
  -9.14561074e-01  1.08711461e+00 -6.33608597e-01 -5.85369407e-01]
 [-6.49742082e-01  1.01047149e+00 -1.37269076e+00 -7.76894160e-01
  -1.24829028e+00  8.00640769e-01 -1.38169856e+00  1.07578035e+00
   3.80955061e-01  1.08711461e+00 -6.33608597e-01 -5.85369407e-01]
 [ 1.28415013e+00 -9.89637026e-01  7.37450360e-01 -1.47555308e+00
   1.38408397e+00  8.00640769e-01  7.23746864e-01 -9.29557782e-01
   1.24307013e+00 -9.19866211e-01  1.57826141e+00 -5.85369407e-01]
 [-5.53528539e-01  1.01047149e+00  7.37450360e-01  2.71094215e-01
  -1.24829028e+00 -9.07392872e-01 -1.38169856e+00 -9.29557782e-01
   9.69966209e-01 -9.19866211e-01 -6.33608597e-01  1.70832296e+00]
 [ 2.93150638e-01 -9.89637026e-01 -1.79471898e+00  9.69753132e-01
   3.48715983e-01 -9.07392872e-01  7.23746864e-01 -9.29557782e-01
  -1.45115075e+00  1.08711461e+00 -6.33608597e-01 -5.85369407e-01]
 [-1.59263480e+00  1.01047149e+00  2.09915080e-01 -1.47555308e+00
  -1.24829028e+00  8.00640769e-01 -1.38169856e+00 -9.29557782e-01
   2.17024046e-01  1.08711461e+00 -6.33608597e-01 -5.85369407e-01]
 [-2.45645202e-01  1.01047149e+00  5.26436248e-01 -1.47555308e+00
   7.84418815e-01 -9.07392872e-01  7.23746864e-01  1.07578035e+00
   1.89691353e-01  1.08711461e+00 -6.33608597e-01 -5.85369407e-01]
 [-2.19878012e+00 -9.89637026e-01  3.15422136e-01  1.66841205e+00
   7.35354993e-01  8.00640769e-01  7.23746864e-01 -9.29557782e-01
  -7.07008333e-02 -9.19866211e-01  1.57826141e+00 -5.85369407e-01]
 [-1.54452803e+00 -9.89637026e-01 -3.17620200e-01  6.20423674e-01
   9.24946326e-01 -9.07392872e-01  7.23746864e-01  1.07578035e+00
  -1.29460915e+00 -9.19866211e-01 -6.33608597e-01  1.70832296e+00]
 [-3.70722807e-01  1.01047149e+00 -8.45155480e-01  9.69753132e-01
   1.67885246e+00  8.00640769e-01  7.23746864e-01  1.07578035e+00
  -1.73187451e+00 -9.19866211e-01 -6.33608597e-01  1.70832296e+00]
 [-7.94062396e-01  1.01047149e+00  4.20929192e-01 -1.12622362e+00
   3.78994134e-01 -9.07392872e-01 -1.38169856e+00 -9.29557782e-01
  -2.68968593e-01  1.08711461e+00 -6.33608597e-01 -5.85369407e-01]
 [-1.40982907e+00  1.01047149e+00  4.20929192e-01 -7.76894160e-01
   1.21994502e+00 -9.07392872e-01  7.23746864e-01  1.07578035e+00
  -8.43773786e-01 -9.19866211e-01  1.57826141e+00 -5.85369407e-01]
 [ 8.14808441e-02  1.01047149e+00  2.10904209e+00 -1.47555308e+00
   9.04404769e-01 -9.07392872e-01  7.23746864e-01 -9.29557782e-01
  -1.67701300e+00 -9.19866211e-01  1.57826141e+00 -5.85369407e-01]
 [ 1.09172304e+00 -9.89637026e-01 -5.28634312e-01  6.20423674e-01
  -1.24829028e+00  8.00640769e-01 -1.38169856e+00 -9.29557782e-01
  -3.34475439e-01  1.08711461e+00 -6.33608597e-01 -5.85369407e-01]
 [-6.11256665e-01 -9.89637026e-01 -4.23127256e-01 -1.47555308e+00
   4.01635740e-01 -9.07392872e-01  7.23746864e-01 -9.29557782e-01
   1.38350478e-01 -9.19866211e-01  1.57826141e+00 -5.85369407e-01]
 [ 1.48830324e-01  1.01047149e+00 -7.39648424e-01  1.31908259e+00
   7.84058904e-01  8.00640769e-01  7.23746864e-01  1.07578035e+00
   6.45780964e-01 -9.19866211e-01  1.57826141e+00 -5.85369407e-01]
 [ 1.97688764e+00  1.01047149e+00 -2.12113144e-01  6.20423674e-01
  -1.24829028e+00 -9.07392872e-01  7.23746864e-01  1.07578035e+00
  -1.06148313e+00  1.08711461e+00 -6.33608597e-01 -5.85369407e-01]]

In [14]:
with open('scaler.pkl','wb') as file:
    pickle.dump(scaler,file)

In [15]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.callbacks import EarlyStopping , TensorBoard
import datetime

In [16]:
X_train.shape[1]

12

In [17]:
## Build Our ANN Model
model = Sequential([
    Dense(64,activation='relu',input_shape=(X_train.shape[1],)),
    Dense(32,activation='relu'),
    Dense(1,activation='sigmoid'),
])

E:\ANN_projects\venv\lib\site-packages\keras\src\layers\core\dense.py:95: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [18]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━┓
┃ Layer (type)              ┃ Output Shape        ┃    Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━┩
│ dense (Dense)             │ (None, 64)          │        832 │
├───────────────────────────┼─────────────────────┼────────────┤
│ dense_1 (Dense)           │ (None, 32)          │      2,080 │
├───────────────────────────┼─────────────────────┼────────────┤
│ dense_2 (Dense)           │ (None, 1)           │         33 │
└───────────────────────────┴─────────────────────┴────────────┘

 Total params: 2,945 (11.50 KB)

 Trainable params: 2,945 (11.50 KB)

 Non-trainable params: 0 (0.00 B)

In [19]:
import tensorflow
opt=tensorflow.keras.optimizers.Adam(learning_rate=0.01)
loss=tensorflow.keras.losses.BinaryCrossentropy()
loss

In [20]:
model.compile(optimizer=opt,loss="binary_crossentropy", metrics=['accuracy'])

WARNING:tensorflow:TensorFlow GPU support is not available on native Windows for TensorFlow >= 2.11. Even if CUDA/cuDNN are installed, GPU will not be used. Please use WSL2 or the TensorFlow-DirectML plugin.

In [21]:
## Setup the tensorboard 
from tensorflow.keras.callbacks import EarlyStopping,TensorBoard
log_dir = 'logs/fit' + datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
tensorflow_callback = TensorBoard(log_dir=log_dir , histogram_freq=1)

In [22]:
## Set up Early Stopping 
early_stopping_callback = EarlyStopping(monitor='val_loss',patience=10,restore_best_weights=True)

In [23]:
## Traning the model

history = model.fit(
    X_train , Y_train , validation_data = (X_test,Y_test) , epochs = 100,
    callbacks=[tensorflow_callback,early_stopping_callback]
)

Epoch 1/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 6s 225ms/step - accuracy: 0.7812 - loss: 0.5196 - val_accuracy: 0.7292 - val_loss: 0.7320
Epoch 2/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 1s 73ms/step - accuracy: 0.8125 - loss: 0.3981 - val_accuracy: 0.7083 - val_loss: 0.5605
Epoch 3/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 1s 65ms/step - accuracy: 0.8438 - loss: 0.3411 - val_accuracy: 0.7917 - val_loss: 0.5749
Epoch 4/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 1s 62ms/step - accuracy: 0.8906 - loss: 0.3115 - val_accuracy: 0.8125 - val_loss: 0.7232
Epoch 5/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 1s 58ms/step - accuracy: 0.8906 - loss: 0.2608 - val_accuracy: 0.7917 - val_loss: 0.7360
Epoch 6/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 86ms/step - accuracy: 0.8854 - loss: 0.2260 - val_accuracy: 0.7708 - val_loss: 0.7692
Epoch 7/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 1s 63ms/step - accuracy: 0.9115 - loss: 0.1904 - val_accuracy: 0.7917 - val_loss: 0.8378
Epoch 8/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 1s 64ms/step - accuracy: 0.9427 - loss: 0.1545 - val_accuracy: 0.8125 - val_loss: 0.8796
Epoch 9/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - accuracy: 0.9635 - loss: 0.1264 - val_accuracy: 0.8125 - val_loss: 0.9149
Epoch 10/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 1s 64ms/step - accuracy: 0.9635 - loss: 0.1022 - val_accuracy: 0.7917 - val_loss: 0.9771
Epoch 11/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 1s 60ms/step - accuracy: 0.9896 - loss: 0.0733 - val_accuracy: 0.8125 - val_loss: 1.1090
Epoch 12/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 1s 59ms/step - accuracy: 0.9740 - loss: 0.0666 - val_accuracy: 0.7917 - val_loss: 1.1360

In [29]:
model.save("model.keras")

In [30]:
%load_ext tensorboard

The tensorboard extension is already loaded. To reload it, use:
  %reload_ext tensorboard

In [31]:
%tensorboard --logdir logs/fit20260503-221339

Reusing TensorBoard on port 6008 (pid 13728), started 0:00:01 ago. (Use '!kill 13728' to kill it.)