In [2]:
import pandas as pd
import numpy as np

data = pd.read_excel("diabetes_dataset_120_cases.xlsx")
data

,age,hypertension,heart_disease,smoking_history,bmi,HbA1c_level,blood_glucose_level,diabetes
0,54,1,0,never,29.9,7.6,162,1
1,34,0,1,former,33.5,6.3,273,1
2,58,0,0,never,20.0,5.9,234,0
3,80,0,0,former,22.1,4.2,182,0
4,23,1,0,ever,27.1,5.3,230,0
...,...,...,...,...,...,...,...,...
115,78,0,0,not current,29.1,5.9,270,0
116,31,0,0,not current,18.6,6.0,73,0
117,47,0,1,former,22.3,3.5,174,0
118,39,0,0,not current,35.8,5.6,183,0
119,69,0,0,never,15.0,5.7,116,0

In [3]:
df = data
df['smoking_history'].unique()

array(['never', 'former', 'ever', 'not current', 'current'], dtype=object)

In [4]:
from sklearn.preprocessing import LabelEncoder
label_encoder = LabelEncoder()

df['smoking_history'] = label_encoder.fit_transform(df['smoking_history'])

In [5]:
df

,age,hypertension,heart_disease,smoking_history,bmi,HbA1c_level,blood_glucose_level,diabetes
0,54,1,0,3,29.9,7.6,162,1
1,34,0,1,2,33.5,6.3,273,1
2,58,0,0,3,20.0,5.9,234,0
3,80,0,0,2,22.1,4.2,182,0
4,23,1,0,1,27.1,5.3,230,0
...,...,...,...,...,...,...,...,...
115,78,0,0,4,29.1,5.9,270,0
116,31,0,0,4,18.6,6.0,73,0
117,47,0,1,2,22.3,3.5,174,0
118,39,0,0,4,35.8,5.6,183,0
119,69,0,0,3,15.0,5.7,116,0

In [6]:
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
scaled_data = scaler.fit_transform(df)
pac1 = PCA(n_components=2)
pca2 = PCA(n_components=0.80)

pca_data = pac1.fit_transform(scaled_data)
pca_data2 = pca2.fit_transform(scaled_data)

pca_df = pd.DataFrame(pca_data , columns=['PC1','PC2'])

In [7]:
print("Explained variance by each principal componenet:" , pac1.explained_variance_ratio_)

print(pca_df)

Explained variance by each principal componenet: [0.23153541 0.16039591]
          PC1       PC2
0    1.505696 -0.118044
1    2.094873  0.320668
2   -0.859311 -0.603860
3   -1.719087 -1.411069
4    0.767324 -0.643626
..        ...       ...
115 -0.750696 -0.117345
116 -2.108386  0.078125
117 -1.322502 -1.897057
118 -0.924115  1.373623
119 -2.114572 -1.231596

[120 rows x 2 columns]

In [9]:
pca_df2 = pd.DataFrame(pca_data2)
pca_df2

            0         1         2         3         4         5
0    1.505696 -0.118044  1.991587  0.018698  0.069389  1.249753
1    2.094873  0.320668 -0.762322  2.165736 -0.692883  0.159040
2   -0.859311 -0.603860  0.635845 -0.850842 -0.912472 -0.643536
3   -1.719087 -1.411069  0.184406 -0.491235  0.952730 -0.785301
4    0.767324 -0.643626 -1.484859 -1.547144 -0.185397  0.982724
..        ...       ...       ...       ...       ...       ...
115 -0.750696 -0.117345  1.259226 -0.275145  0.121919  0.508508
116 -2.108386  0.078125  0.536930 -0.206638 -1.762735 -0.170080
117 -1.322502 -1.897057 -1.952021  1.503699 -0.474239 -0.483097
118 -0.924115  1.373623 -0.085070  0.226165 -0.067806  1.576189
119 -2.114572 -1.231596  1.232117 -0.460980 -0.649637 -1.258756

[120 rows x 6 columns]