In [1]:
import tensorflow as tf
from tensorflow.keras.models import load_model
import pickle
import pandas as pd
import numpy as np

In [2]:
## Load the trained model , scaler pickel , onehot
model = load_model('model.h5')

with open('onehot_encoding_geo.pkl','rb') as file:
    label_encoder_geo = pickle.load(file)

## Load the encoder and scaler
with open('label_encoder_gender.pkl','rb') as file:
    label_encoder_gender = pickle.load(file)


with open('scaler.pkl','rb') as file:
    scaler = pickle.load(file)

WARNING:tensorflow:TensorFlow GPU support is not available on native Windows for TensorFlow >= 2.11. Even if CUDA/cuDNN are installed, GPU will not be used. Please use WSL2 or the TensorFlow-DirectML plugin.

WARNING:absl:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

In [30]:
import pandas as pd

# Your original dict
input_data = {
    'CreditScore': 600,
    'Geography': 'France',
    'Gender': 'Male',
    'Age': 40,
    'Tenure': 3,   # ✅ ADD THIS
    'Balance': 60000,
    'NumOfProducts': 2,
    'HasCrCard': 1,
    'IsActiveMember': 1,
    'EstimatedSalary': 50000
}

In [31]:
geo_encoded = label_encoder_geo.transform([[input_data["Geography"]]]).toarray()
geo_encoded_df = pd.DataFrame(geo_encoded,columns=label_encoder_geo.get_feature_names_out(["Geography"]))
geo_encoded_df

e:\ANN_projects\venv\lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(

   Geography_France  Geography_Germany  Geography_Spain
0               1.0                0.0              0.0

In [35]:
input_df = pd.DataFrame([input_data])
input_df

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary
0,600,France,Male,40,3,60000,2,1,1,50000

In [36]:
input_df['Gender'] = label_encoder_gender.transform(input_df['Gender'])
input_df

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary
0,600,France,1,40,3,60000,2,1,1,50000

In [38]:
input_df = pd.concat([input_df.drop("Geography" , axis=1) , geo_encoded_df],axis=1 )
input_df

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Geography_France,Geography_Germany,Geography_Spain
0,600,1,40,3,60000,2,1,1,50000,1.0,0.0,0.0

In [40]:
## Scaling the nput Data 
input_scaled = scaler.transform(input_df)
input_scaled

array([[-0.42845093,  1.01047149,  0.20991508, -0.77689416, -0.27424128,
         0.80064077,  0.72374686,  1.07578035, -0.90314916,  1.08711461,
        -0.6336086 , -0.58536941]])

In [41]:
# prediction Chrun 
prediction = model.predict(input_scaled)
prediction

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 157ms/step

array([[0.01684044]], dtype=float32)

In [44]:
prediction_proba = prediction[0][0]

In [45]:
prediction_proba

np.float32(0.016840443)

In [47]:
if prediction_proba >0.5:
    print("The customer is likely to churn.")

else:
    print("The customer is not likely to churn")

The customer is not likely to churn